### ISSUE TITLE
New NuGet build

### ISSUE THREAD

**Issue by kevfromireland** [bytenik/MongoDB.Embedded#3]
Hey,

Now that @spencerthang has submitted the PR for new Mongo, would it be possible to get a new package pushed to NuGet? 

Alternatively, I'm happy to take ownership of this in the red-gate org if you guys aren't using it any more and you want to transfer ownership of it?

**Comment by bytenik** [comment]
Sure, if Red Gate wants to take ownership, be my guest. We do use it, but only rarely. It'd be great to have someone else taking care of it. :)

**Comment by bytenik** [comment]
Can't transfer it to you because you already have a fork.

**Comment by johnknoop** [comment]
Regardless of who takes ownership, can you please push the new version to Nuget?

**Comment by kevfromireland** [comment]
Can you transfer it to github.com/red-gate rather than me? Better it goes to the company org.

**Comment by bytenik** [comment]
Unfortunately not. I already transferred it from my org to me, but GitHub only lets you transfer between yourself and orgs you are an admin on. I can transfer to you and you can transfer to red-gate.

**Comment by kevfromireland** [comment]
Deleted. Transfer now please.

**Comment by faxedhead** [comment]
Could someone please upload the latest version of this to nuget, the c# 2.0 driver support is needed, thanks!

**Comment by bytenik** [comment]
@kevfromireland Are you no longer transferring it over to RedGate?

![image](https://cloud.githubusercontent.com/assets/441347/12081132/f7d7ecc0-b23e-11e5-871e-643bb4a8eb06.png)

Its been like this for a few months.

**Comment by kevfromireland** [comment]
I tried to migrate it to the RG org, but as we already had a fork it didn't allow me. Other things have gotten in the way though and we have migrated to Postgres so I don't think I'll be a good stewart for this project any more as we aren't building on it. Apologies for leaving it in limbo.
